spring:
  profiles:
    active: development

---
spring:
  profiles: development
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false
    username: root
    password: 123456

---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE